apiVersion: app/v1
kind: deployment
metadata: 
   name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
       apps: gcp
  template:
    metadata:
       labels:
         app: gcp
    spec:
      containers:
      - name :
        image:
        port:
        - containerPort: 5000
        env:
          - name:
            value: 
